apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage-claim
  namespace: azurephotoflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi  # Adjust based on your storage needs
  # storageClassName: your-storage-class  # Uncomment and specify if needed