apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  namespace: azurephotoflow
  labels:
    app: qdrant
spec:
  selector:
    app: qdrant
  ports:
  - name: rest-api
    port: 6333
    targetPort: 6333
    protocol: TCP
  - name: grpc
    port: 6334
    targetPort: 6334
    protocol: TCP
  type: ClusterIP