services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  backend:
    image: "${CONTAINER_REGISTRY}/azurephotoflow-backend:${stableTag:-latest}"
    build:
      context: .
      dockerfile: backend/AzurePhotoFlow.Api/Dockerfile
      args:
        CERTIFICATE_PASSWORD: ${CERTIFICATE_PASSWORD}
        AZURE_BLOB_STORAGE: ${AZURE_BLOB_STORAGE}
        CERTIFICATE_PATH: ${CERTIFICATE_PATH}
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        MODE: ${MODE}
        MINIO_ENDPOINT: ${MINIO_ENDPOINT:-http://minio:9000}
        MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
        MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
    container_name: backend
    volumes:
      - ./models:/models
    environment:
      - ASPNETCORE_URLS=http://+:80
      - AZURE_BLOB_STORAGE=${AZURE_BLOB_STORAGE}
      - CERTIFICATE_PATH=${CERTIFICATE_PATH}
      - CERTIFICATE_PASSWORD=${CERTIFICATE_PASSWORD}
      - MODE=${MODE}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-http://minio:9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
      - CLIP_MODEL_PATH=${CLIP_MODEL_PATH:-/models/model.onnx}
      - ENABLE_EMBEDDINGS=${ENABLE_EMBEDDINGS:-false}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost}
    networks:
      - app-network
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - app-network

  frontend:
    image: "${CONTAINER_REGISTRY}/azurephotoflow-frontend:${stableTag:-latest}"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        MODE: ${MODE:-development}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    container_name: frontend
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - MODE=${MODE}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  minio-data:
