services:
  backend-api:
    build:
      context: ./backend/AzurePhotoFlow.Api
      dockerfile: Dockerfile
    environment:
      - AZURE_BLOB_STORAGE
      - CERTIFICATE_PATH
      - CERTIFICATE_PASSWORD
    volumes:
      - ./certs:/app/certs:ro
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - backend-functions

  backend-functions:
    build:
      context: ./backend/AzurePhotoFlow.Functions
      dockerfile: Dockerfile
    ports:
      - "5001:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        MODE: development
    environment:
      - VITE_API_BASE_URL
    ports:
      - "3000:80"
    depends_on:
      - backend-api

  terraform:
    build:
      context: ./infrastructure
      dockerfile: Dockerfile
    volumes:
      - "./infrastructure:/terraform"
    working_dir: /terraform

