services:
  backend-api:
    build:
      context: ./backend/AzurePhotoFlow.Api
      dockerfile: Dockerfile
    environment:
      - AZURE_BLOB_STORAGE=${AZURE_BLOB_STORAGE}
      - CERTIFICATE_PATH=${CERTIFICATE_PATH}
      - CERTIFICATE_PASSWORD=${CERTIFICATE_PASSWORD}
    volumes:
      - ./certs:/app/certs:ro
    ports:
      - "8080:80"
      - "8443:443"
    # depends_on:
    #   - backend-functions
    networks:
      - app-network

  # backend-functions:
  #   build:
  #     context: ./backend/AzurePhotoFlow.Functions
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5001:80"
  #   networks:
  #     - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        MODE: ${MODE:-development}
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "3000:80"
    depends_on:
      - backend-api
    networks:
      - app-network

  terraform:
    build:
      context: ./infrastructure
      dockerfile: Dockerfile
    volumes:
      - "./infrastructure:/terraform"
    working_dir: /terraform

networks:
  app-network:
    driver: bridge

