apiVersion: v1
kind: ConfigMap
metadata:
  name: azurephotoflow-config
  namespace: azurephotoflow
data:
  # Application configuration
  MODE: "production"
  QDRANT_URL: "http://qdrant-service:6333"
  QDRANT_COLLECTION: "images"
  CLIP_MODEL_PATH: "/models/model.onnx"
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_BUCKET: "photostore"
  ALLOWED_ORIGINS: "https://your-domain.com,http://localhost:3000"
  ENABLE_EMBEDDINGS: "true"
  VITE_API_BASE_URL: "https://your-domain.com/api"
  # Logging
  ASPNETCORE_ENVIRONMENT: "Production"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft: "Warning"