apiVersion: v1
kind: Secret
metadata:
  name: azurephotoflow-secrets
  namespace: azurephotoflow
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # To encode: echo -n "your-value" | base64
  VITE_GOOGLE_CLIENT_ID: "REPLACE_WITH_BASE64_ENCODED_VALUE"
  JWT_SECRET_KEY: "REPLACE_WITH_BASE64_ENCODED_VALUE" 
  MINIO_ACCESS_KEY: "bWluaW9hZG1pbg=="  # minioadmin
  MINIO_SECRET_KEY: "bWluaW9hZG1pbg=="  # minioadmin
  QDRANT_API_KEY: ""  # Optional - leave empty if not using authentication
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: azurephotoflow
type: kubernetes.io/dockerconfigjson
data:
  # Docker registry credentials for pulling images from GHCR
  # Create with: kubectl create secret docker-registry registry-secret \
  #   --docker-server=ghcr.io \
  #   --docker-username=YOUR_GITHUB_USERNAME \
  #   --docker-password=YOUR_GITHUB_TOKEN \
  #   --namespace=azurephotoflow
  .dockerconfigjson: "REPLACE_WITH_DOCKER_CONFIG_JSON"