apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: azurephotoflow
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP