title: AzurePhotoFlow
description: Cloud-native AI-powered photo management with open-source technologies
remote_theme: pages-themes/minimal@v0.2.0
baseurl: "/AzurePhotoFlow"
url: "https://loicniragire.github.io"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

header_pages:
  - architecture.md
  - api_endpoints.md
  - setup.md
  - CICD_DEPLOYMENT.md

exclude:
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - Gemfile
  - Gemfile.lock
  - "*.gemspec"